

IF NOT EXISTS(SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'GERARXMLCEST' AND TYPE = 'U') 
CREATE TABLE GERARXMLCEST(
	CEST VARCHAR(15) NULL,
	NCM VARCHAR(17) NULL,
	DESCRICAO VARCHAR(500) NULL
)
GO

SELECT '<?XML VERSION="1.0" ENCODING="UTF-8" STANDALONE="YES"?>' LINHA UNION ALL
SELECT '<DATAPACKET VERSION="2.0">' LINHA UNION ALL
SELECT '<METADATA>' LINHA UNION ALL
SELECT '<FIELDS>' LINHA UNION ALL
SELECT '<FIELD WIDTH="20" SUBTYPE="FIXEDCHAR" FIELDTYPE="STRING" ATTRNAME="COD_CEST"/>' LINHA UNION ALL
SELECT '<FIELD WIDTH="20" SUBTYPE="FIXEDCHAR" FIELDTYPE="STRING" ATTRNAME="COD_NCM"/>' LINHA UNION ALL
SELECT '<FIELD WIDTH="255" SUBTYPE="FIXEDCHAR" FIELDTYPE="STRING" ATTRNAME="DESCRICAO"/>' LINHA UNION ALL
SELECT '</FIELDS>' LINHA UNION ALL
SELECT '<PARAMS LCID="2057"/>' LINHA UNION ALL
SELECT '</METADATA>' LINHA UNION ALL
SELECT '<ROWDATA>' LINHA UNION ALL

SELECT*FROM
(SELECT '<ROW COD_CEST="' + ISNULL(CEST, '0000000') + '" COD_NCM="' + ISNULL(CONVERT(VARCHAR, NCM), '0') +'" DESCRICAO="' + SUBSTRING(REPLACE(DESCRICAO, '"', ''), 1, 250) + '"/>' LINHA FROM GERARXMLCEST)T WHERE LINHA IS NOT NULL
UNION ALL
SELECT '</ROWDATA>' LINHA UNION ALL
SELECT '</DATAPACKET>' LINHA



 
